### ISSUE TITLE
get_mac_form_switches.py crashes on operation timeout

### ISSUE THREAD

**Issue by apofiget** [infery/zabbix-map-creator#1]
Hi! Thank you for your software! It's very helpfull!
But, when we've try execute get_mac_form_switches.py script, we got back 
these error:

> Connect to 10.245.185.2 , vendor dlink
> Traceback (most recent call last):
>   File "./get_mac_form_switches.py", line 100, in <module>
>     mac_table = dlink.get_mac_address_table(sw_ip, sw_username, sw_password)
>   File "/home/sphinx/tmp/0/zabbix-map-creator/dlink.py", line 31, in get_mac_address_table
>     ret = t.expect(['#', 'All']) 
>   File "/usr/lib/python2.7/dist-packages/pexpect/spawnbase.py", line 321, in expect
>     timeout, searchwindowsize, async)
>   File "/usr/lib/python2.7/dist-packages/pexpect/spawnbase.py", line 345, in expect_list
>     return exp.expect_loop(timeout)
>   File "/usr/lib/python2.7/dist-packages/pexpect/expect.py", line 107, in expect_loop
>     return self.timeout(e)
>   File "/usr/lib/python2.7/dist-packages/pexpect/expect.py", line 70, in timeout
>     raise TIMEOUT(msg)
> pexpect.exceptions.TIMEOUT: Timeout exceeded.
> <pexpect.pty_spawn.spawn object at 0x7f6c935c4f10>
> command: /usr/bin/telnet
> args: ['/usr/bin/telnet', '10.245.185.2']
> buffer (last 100 chars): '            34:08:04:e2:02:f8 1:15  dynamic\r\n304  VoIP             34:08:04:e2:03:18 1:9   dynamic\r\n'
> before (last 100 chars): '            34:08:04:e2:02:f8 1:15  dynamic\r\n304  VoIP             34:08:04:e2:03:18 1:9   dynamic\r\n'
> after: <class 'pexpect.exceptions.TIMEOUT'>
> match: None
> match_index: None
> exitstatus: None
> flag_eof: False
> pid: 6141
> child_fd: 5
> closed: False
> timeout: 30
> delimiter: <class 'pexpect.exceptions.EOF'>
> logfile: None
> logfile_read: None
> logfile_send: None
> maxread: 2000
> ignorecase: False
> searchwindowsize: None
> delaybeforesend: 0.05
> delayafterclose: 0.1
> delayafterterminate: 0.1
> searcher: searcher_re:
>     0: re.compile("#")
>     1: re.compile("All")

Is it bug?

**Comment by infery** [comment]
May be this is slow dlink cli and small timeout value. Added timeout option in pexpect. Please, clone and try again.
You can try `./dlink.py 10.245.185.2 admin admin`

**Comment by apofiget** [comment]
Thanks! We'll try.
