### ISSUE TITLE
Получение FDB для D-Link DES-1100 с прошивкой ME

### ISSUE THREAD

**Issue by roysbike** [infery/zabbix-map-creator#3]
Проблема с парсером  FDB таблицы от DES-1100-16/24 (ME прошивка), так как не имеет столбца VLAN. Вот вывод fdb таблицы

```
Port  MAC Address        Type
----  -----------------  -------  
16    90-94-E4-D5-00-05  Dynamic
16    28-3B-82-E6-90-0E  Dynamic
16    EC-22-80-6E-40-1E  Dynamic
16    5C-D9-98-9A-50-21  Dynamic
16    F8-E9-03-D1-D0-26  Dynamic
16    E8-CC-18-72-C0-28  Dynamic
16    58-D5-6E-3B-D0-30  Dynamic
16    40-9B-CD-FE-50-36  Dynamic
16    28-3B-82-E6-90-3E  Dynamic
16    14-D6-4D-04-F0-40  Dynamic
16    E8-CC-18-7C-C0-45  Dynamic
16    40-9B-CD-FE-10-46  Dynamic
16    10-62-EB-53-80-52  Dynamic
16    A0-AB-1B-FE-F0-55  Dynamic
16    F8-E9-03-D1-D0-56  Dynamic
16    E8-CC-18-6E-D0-58  Dynamic
16    9C-D6-43-5E-50-5B  Dynamic
16    58-D5-6E-3B-D0-60  Dynamic
```

Если можно, то добавьте пожалуйста

**Comment by infery** [comment]
Покажите, пожалуйста, вывод команды `show switch`

**Comment by roysbike** [comment]
> Покажите, пожалуйста, вывод команды `show switch`
Эту прошивку выпустил dlink , чтобы хоть как-то можно было управлять свичем) Это DES-1100-16/24 Smart 


```

CMD>>admin#sh sw
Command: show switch 


MAC Address      : C8-BE-19-D6-03-B4
IP Address       : 172.16.22.117
VLAN Name        : 2
Subnet Mask      : 255.255.252.0
Default Gateway  : 172.16.20.2
Boot PROM Version: 1.0.1
Firmware Version : 3.00.R013
System Name      : 
System Location  : 
System Contact   : 
Spanning Tree    : Enabled
IGMP Snooping    : Disabled

```

**Comment by infery** [comment]
done

**Comment by roysbike** [comment]
Работает! Спасибо!

**Comment by infery** [comment]
http://forum.dlink.ru/viewtopic.php?f=2&t=160918&start=315#p951968
пишут, что постраничный вывод fdb не отключается. Если то, что есть, не отрабатывает, пришлите снимок экрана, где свич предлагает нажать какую-либо клавишу, чтобы я мог отловить это

**Comment by roysbike** [comment]
> http://forum.dlink.ru/viewtopic.php?f=2&t=160918&start=315#p951968
> пишут, что постраничный вывод fdb не отключается. Если то, что есть, не отрабатывает, пришлите снимок экрана, где свич предлагает нажать какую-либо клавишу, чтобы я мог отловить это

Да. Работает, но только хорошо отображается на uplink.

![image](https://user-images.githubusercontent.com/2388223/55705633-deb17500-59e7-11e9-9d8b-ba69c9170d7c.png)
![image](https://user-images.githubusercontent.com/2388223/55705682-01dc2480-59e8-11e9-8e1c-7b2807024761.png)

**Comment by infery** [comment]
Если не мешает, можем оставить как есть. Или продолжить с этим коммутатором. 
Для этого раскомментируйте, пожалуйста, строки 
```
8: # import sys
14: # t.logfile = sys.stdout
```
выполните `./dlink.py 172.16.22.117 login pass`
И прикрепите в виде текста все, что там будет. Посмотрим, что выводит свич.
Спасибо

**Comment by roysbike** [comment]
disable clipaging команды он не знает 
[1100_dump.txt](https://github.com/infery/zabbix-map-creator/files/3053250/1100_dump.txt)

Наверное какую-то строку парсит
da:c выскакивает на любом свиче 1100.
![image](https://user-images.githubusercontent.com/2388223/55708303-44086480-59ee-11e9-993f-39695729d3cc.png)
А так все верно получает

**Comment by infery** [comment]
Спасибо, поправил одно место. Думаю дело было в записи CPU. А то, что clipaging не знает - это норм. Некоторые свичи знают, но все равно не отключают, поэтому пришлось предусмотреть
